### ISSUE TITLE
File paths are way too long

### ISSUE THREAD

**Issue by Lokathor** [google/shaderc-rs#33]
The build process should attempt to use shorter paths.

When attempting to build shaderc-rs, @termhn was given the following error

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "x64\Release\spirv-tools-spv-amd-shader-explicit-vertex-parameter\spirv-to.8AECBDF2.tlog\spirv-tools-spv-amd-shader-explicit-vertex-parameter.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\Gray\Code\learn-gfx-hal\target\debug\build\shaderc-ceea3062217d891f\out\build\spirv-tools\source\spirv-tools-spv-amd-shader-explicit-vertex-parameter.vcxproj]

And then it was fixed by just moving up from `C:\Users\Gray\Code\learn-gfx-hal` to `C:\dev\learn-gfx-hal`, so you're right on the limit I guess, shouldn't be too hard to cut down some of the wordy stuff.

**Comment by antiagainst** [comment]
Yes, agreed. I also noticed this issue on buildbot recently and had a temporary solution (https://github.com/google/shaderc-rs/commit/3d6fa5c6c5d9e594193355cd835d792b776e4d06). Looking for better ways now.

The long path is because both the default Rust `target/` directory organization (attaching the super long `target\x86_64-pc-windows-msvc\debug\build\shaderc-ceea3062217d891f\out\build` component to the path if you build towards `x86_64-pc-windows-msvc`) and the target names in SPIRV-Tools (`spirv-tools-spv-amd-shader-explicit-vertex-parameter`). Arguably the first part carries more weight.

Funnily we are in the year of 2019 now, yet still suffer from some limitation from DOS time. MSBuild should really be modernized: https://github.com/Microsoft/msbuild/issues/53.

**Comment by antiagainst** [comment]
As a temporary workaround, you can use `cargo --target-dir`. See [.appveyor.yml](https://github.com/google/shaderc-rs/blob/master/.appveyor.yml).

**Comment by antiagainst** [comment]
I've merged https://github.com/google/shaderc-rs/pull/38, which will detect whether Ninja exists in `PATH` and use it if true. It's pulling in another dependency (which is likely already installed on C++ dev machines), but Ninja is generally faster than MSBuild and does not suffer from `MAX_PATH` issue.

To make MSBuild work means to trim down the path. As discussed in https://github.com/google/shaderc-rs/issues/33#issuecomment-455179634, neither the default Rust target directory organization nor the SPIRV-Tools target name is easy to trim down for that purpose. And both of them can change again in the future.

**Comment by Lokathor** [comment]
The existence of this workaround should also be explicitly documented in the `README.md`

**Comment by antiagainst** [comment]
@Lokathor, it's already documented in README with https://github.com/google/shaderc-rs/commit/a4f1bccf3d867e85fdd6924998122b7b8d0c8904.

**Comment by Lokathor** [comment]
oh! so it is, foolish me
